Algoritmo "semnome"
//  
//  
// Descrição   : Identifica par ou impar
// Autor(a)    : Iuri de Carvalho Salgado
// Data atual  : 21/08/2022
Var
// Seção de Declarações das variáveis 
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite um numero")
leia(numero)

se numero mod 2 = 0 entao
   escreval("O numero e par")
senao
     escreval("O numero e impar")
fimse

Fimalgoritmo