Algoritmo "tabuada"
//  
//  
// Descrição   : Algoritmo da tabuada
// Autor(a)    : Iuri de Carvalho Salgado
// Data atual  : 30/08/2022
Var
// Seção de Declarações das variáveis 
n, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 1
escreval("informe um valor par a n")
leia(n)

enquanto i <= 10 faca
         escreval(i, " x ", n, " = ", n*i)
         i <- i + 1
fimenquanto



Fimalgoritmo